__default__:
  prefix: "--gres=lscratch:20 --time=4:00:00 --mem=6g"

bwa_index:
  prefix: "--gres=lscratch:20 --time=4:00:00 --mem=32g"

align_reads:
  prefix: "--gres=lscratch:20 --time=54:00:00 --mem=32g"

small_fastq:
  prefix: "--gres=lscratch:100 --time=24:00:00 --mem=64g"

WGS_download_normal:
  prefix: "--gres=lscratch:2000 --time=24:00:00 --mem=64g"

WGS_download_tumor:
  prefix: "--gres=lscratch:2000 --time=24:00:00 --mem=64g"
